# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

exclude: [bibble, README.md, Makefile, screenshot.png]

# colorize code snippets with the pygments module
highlighter: rouge

# The path structure for blog posts.
permalink: /blog/:year/:month/:day/:title.html

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
# title: Glen Berseth
# email: your-email@example.com
description: "I (he/him/il) am an assistant professor at the University de Montreal and Mila. My research explores how to use deep learning and reinforcement learning to develop generalist robots."
### I should add images of Mila, DIRO and UdeM down here.

# description: >- # this means to ignore newlines until "baseurl:"
#   Write an awesome description for your new site here. You can edit this
#   line in _config.yml. It will appear in your document head meta (for
#   Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: jekyllrb
github_username:  neo-x
# youtube_channel: UCa885azMHaNWAEEVeJHTjHw
# youtube_channel_name: chandar-lab
twitter_username: GlenBerseth


gems:
    - jekyll-paginate
    - jekyll/scholar
    - jemoji

# Build settings
encoding: utf-8
markdown: kramdown
theme: minima

plugins:
  - jekyll-redirect-from
  - jekyll-multiple-languages-plugin
  - jekyll-datapage-generator
  - jekyll-scholar

whitelist:
  - jekyll-redirect-from

languages: ["en", "fr"]
exclude_from_localizations: ["assets/images", "youtube.html"]

header_pages:
  - index.html
  - people.html
  - publications.html
  - join.html
  - posts.html
  - teaching.html

page_gen:
  - data: people
    template: profile
    name: name
    dir: people
  - data: alumni
    template: profile
    name: name
    dir: people
    filter: profile_page
    
# Jekyll-Scholar
scholar:

  style: apa
  locale: en

  sort_by: year
  order: descending
#   bibliography_template: bib
  
  replace_strings: true
  join_strings: true
  
  details_dir: bibliography
#   details_layout: bibtex.html
  details_link: Details
  
  query: "@*"

  
jquery_version: "1.12.4"
katex_version: "0.7.1"
anchorjs_version: "3.2.2"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
